### ISSUE TITLE
Rethink the data package/classes

### ISSUE THREAD

**Issue by kinggoesgaming** [MinigameCore/MinigameCoreAPI#24]
The current `data.DataType` is simply a string serializer, which technically isnt what sponge defines as data. I want a bit of review on how this is handled so that real data and java serializable data is seemless.

**Comment by Flibio** [comment]
My intent with the MinigameCore data was not to represent Sponge data or follow the ideology of it. The data is meant to allow for easy storing and retrieval of data to and from files. I suppose if you want the data to be seamless the `DataManager` could take in any object and attempt to convert into a `String`, as well as attempt to convert back into the object type.

**Comment by kinggoesgaming** [comment]
Does sponge provide basic java primitives and String DataManipulators? oh and Location

**Comment by Flibio** [comment]
I don't believe they provide primitive `DataManipulators`, but I do not see why they would have to. With the MinigameCore data system, I just wanted to keep it very simple and easy to implement. No need to add an unnecessary amount of complexity to something that could be kept fairly simple.

**Comment by kinggoesgaming** [comment]
Fair point

**Comment by kinggoesgaming** [comment]
closing for now
